### ISSUE TITLE
7/7

### ISSUE THREAD

**Issue by gklezd** [uwseds-sp18/homework-3-awfuldynne#1]
Issues:

- self.assertRaises(ValueError, create_dataframe(HomeworkThreeTest.invalid_file_path)) will throw the exception
Use: 
        self.assertRaises(ValueError, create_dataframe,HomeworkThreeTest.invalid_file_path)
  which will test that the right exception is thrown but will catch it too. No points off but fix it.

**Comment by awfuldynne** [comment]
Updated code to fix not catching the expected exception: 79997af62688a68c440e60fc43f900ecd5f8fecc.
